export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH' | 'OPTIONS';
export type ApiProtocol = 'REST' | 'GraphQL' | 'gRPC' | 'WebSocket';
export type EndpointStatus = 'ready' | 'development' | 'deprecated' | 'missing';
export type AuthType = 'none' | 'apiKey' | 'jwt' | 'oauth2' | 'mtls';
export type EventProtocol = 'kafka' | 'rabbitmq' | 'sns' | 'pubsub' | 'redis';

export interface ApiEndpoint {
  id: string;
  method: HttpMethod;
  path: string;
  serviceName: string;
  summary: string;
  description: string;
  tags: string[];
  status: EndpointStatus;
  useCaseId?: string;
  requirementIds: string[];
  parameters: ApiParameter[];
  requestBody?: ApiRequestBody;
  responses: ApiResponse[];
  security: ApiSecurity[];
  rateLimiting?: RateLimiting;
  dependencies: ApiDependency[];
  generatedEvents: string[];
  createdAt: Date;
  updatedAt: Date;
}

export interface ApiParameter {
  id: string;
  name: string;
  in: 'query' | 'path' | 'header' | 'cookie';
  type: string;
  required: boolean;
  description: string;
  default?: any;
  example?: any;
  schema?: DataSchema;
  source: 'manual' | 'useCase' | 'autogenerated';
}

export interface ApiRequestBody {
  required: boolean;
  contentType: string;
  schemaId: string;
  example?: any;
}

export interface ApiResponse {
  statusCode: number;
  description: string;
  contentType: string;
  schemaId?: string;
  example?: any;
  headers?: Record<string, string>;
}

export interface ApiSecurity {
  type: AuthType;
  scopes: string[];
  description?: string;
}

export interface RateLimiting {
  enabled: boolean;
  limit: number;
  period: 'second' | 'minute' | 'hour' | 'day';
  perUser: boolean;
}

export interface ApiDependency {
  serviceId: string;
  serviceName: string;
  type: 'synchronous' | 'asynchronous' | 'cache' | 'database';
  required: boolean;
  description: string;
}

export interface DataSchema {
  id: string;
  name: string;
  type: 'object' | 'array' | 'string' | 'number' | 'boolean' | 'enum';
  description: string;
  properties: SchemaProperty[];
  required: string[];
  example?: any;
  linkedToDbTable?: string;
  usedInEndpoints: string[];
  createdAt: Date;
}

export interface SchemaProperty {
  id: string;
  name: string;
  type: string;
  required: boolean;
  description: string;
  example?: any;
  validation?: PropertyValidation;
  reference?: string;
}

export interface PropertyValidation {
  minLength?: number;
  maxLength?: number;
  pattern?: string;
  minimum?: number;
  maximum?: number;
  format?: string;
}

export interface ApiEvent {
  id: string;
  name: string;
  description: string;
  sourceService: string;
  triggerEndpoint?: string;
  protocol: EventProtocol;
  topic: string;
  payloadSchemaId: string;
  consumers: EventConsumer[];
  webhooks: Webhook[];
  retryPolicy: RetryPolicy;
  createdAt: Date;
}

export interface EventConsumer {
  id: string;
  serviceName: string;
  description: string;
  status: 'active' | 'inactive' | 'error';
  lastProcessed?: Date;
}

export interface Webhook {
  id: string;
  url: string;
  method: HttpMethod;
  headers: Record<string, string>;
  status: 'active' | 'inactive' | 'error';
  lastTriggered?: Date;
  lastError?: string;
}

export interface RetryPolicy {
  maxAttempts: number;
  backoffType: 'linear' | 'exponential';
  timeoutSeconds: number;
  deadLetterQueue: boolean;
}

export interface ApiService {
  id: string;
  name: string;
  description: string;
  endpointCount: number;
  protocol: ApiProtocol;
  baseUrl?: string;
  version: string;
  status: 'active' | 'development' | 'deprecated';
}

export interface ApiDocumentation {
  id: string;
  format: 'openapi' | 'markdown' | 'postman' | 'asyncapi' | 'confluence';
  content: string;
  lastGenerated: Date;
}

export interface ApiTestCase {
  id: string;
  endpointId: string;
  name: string;
  description: string;
  useCaseId?: string;
  request: {
    method: HttpMethod;
    path: string;
    headers?: Record<string, string>;
    body?: any;
  };
  expectedResponse: {
    statusCode: number;
    body?: any;
    headers?: Record<string, string>;
  };
  status: 'passed' | 'failed' | 'pending';
  lastRun?: Date;
}

export interface CodeGeneration {
  language: 'typescript' | 'java' | 'python' | 'go' | 'csharp';
  framework?: string;
  components: CodeComponent[];
}

export interface CodeComponent {
  type: 'controller' | 'service' | 'repository' | 'dto' | 'validator' | 'test';
  filename: string;
  code: string;
}

export interface ApiQualityMetrics {
  documentationCoverage: number;
  testCoverage: number;
  restfulCompliance: number;
  performanceRating: number;
  issues: QualityIssue[];
  recommendations: string[];
}

export interface QualityIssue {
  id: string;
  severity: 'low' | 'medium' | 'high';
  type: string;
  description: string;
  endpointId?: string;
  autoFixable: boolean;
}
