import { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import Icon from '@/components/ui/icon';
import ApiDashboard from '@/components/api/ApiDashboard';
import EndpointEditor from '@/components/api/EndpointEditor';
import SchemaDesigner from '@/components/api/SchemaDesigner';
import EventDesigner from '@/components/api/EventDesigner';
import DocumentationGenerator from '@/components/api/DocumentationGenerator';
import CodeGenerator from '@/components/api/CodeGenerator';
import { ApiEndpoint, ApiService, ApiEvent, DataSchema } from '@/types/api';
import { apiClient } from '@/lib/apiClient';

export default function ApiDesignPage() {
  const [activeView, setActiveView] = useState<'dashboard' | 'endpoint' | 'schema' | 'event' | 'docs' | 'code'>('dashboard');
  const [selectedEndpoint, setSelectedEndpoint] = useState<ApiEndpoint | undefined>();
  const [services, setServices] = useState<ApiService[]>([]);
  const [endpoints, setEndpoints] = useState<ApiEndpoint[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadData();
  }, []);

  const loadData = async () => {
    try {
      setLoading(true);
      const [servicesData, endpointsData] = await Promise.all([
        apiClient.getServices(),
        apiClient.getEndpoints()
      ]);
      setServices(servicesData as any);
      setEndpoints(endpointsData as any);
    } catch (error) {
      console.error('Failed to load data:', error);
    } finally {
      setLoading(false);
    }
  };

  const mockServices: ApiService[] = [
    { id: '1', name: 'Order Service', description: 'Управление заказами', endpointCount: 12, protocol: 'REST', version: '1.0', status: 'active' },
    { id: '2', name: 'Product Service', description: 'Каталог продуктов', endpointCount: 8, protocol: 'REST', version: '1.0', status: 'active' },
    { id: '3', name: 'User Service', description: 'Пользователи и аутентификация', endpointCount: 6, protocol: 'REST', version: '1.0', status: 'active' },
    { id: '4', name: 'Payment Service', description: 'Обработка платежей', endpointCount: 5, protocol: 'REST', version: '1.0', status: 'active' },
    { id: '5', name: 'Notification Service', description: 'Уведомления и события', endpointCount: 3, protocol: 'REST', version: '1.0', status: 'active' }
  ];

  const mockEndpoints: ApiEndpoint[] = [
    {
      id: '1',
      method: 'GET',
      path: '/api/v1/orders',
      serviceName: 'Order Service',
      summary: 'Get all orders',
      description: 'Возвращает список заказов с поддержкой фильтрации и пагинации',
      tags: ['Orders'],
      status: 'ready',
      useCaseId: 'UC-12',
      requirementIds: ['BR-045', 'BR-046'],
      parameters: [
        { id: '1', name: 'status', in: 'query', type: 'string', required: false, description: 'Статус заказа', source: 'useCase' },
        { id: '2', name: 'limit', in: 'query', type: 'integer', required: false, description: 'Лимит', default: 50, source: 'autogenerated' },
        { id: '3', name: 'offset', in: 'query', type: 'integer', required: false, description: 'Смещение', default: 0, source: 'autogenerated' }
      ],
      responses: [
        { statusCode: 200, description: 'Успешно', contentType: 'application/json', schemaId: 'OrderListResponse' },
        { statusCode: 400, description: 'Неверные параметры', contentType: 'application/json' },
        { statusCode: 401, description: 'Не авторизован', contentType: 'application/json' }
      ],
      security: [{ type: 'jwt', scopes: ['orders.read'], description: 'JWT authentication' }],
      rateLimiting: { enabled: true, limit: 1000, period: 'hour', perUser: true },
      dependencies: [
        { serviceId: 'auth', serviceName: 'Auth Service', type: 'synchronous', required: true, description: 'JWT validation' },
        { serviceId: 'db', serviceName: 'PostgreSQL', type: 'database', required: true, description: 'Read orders' }
      ],
      generatedEvents: [],
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '2',
      method: 'POST',
      path: '/api/v1/orders',
      serviceName: 'Order Service',
      summary: 'Create new order',
      description: 'Создает новый заказ',
      tags: ['Orders'],
      status: 'development',
      useCaseId: 'UC-13',
      requirementIds: ['BR-047'],
      parameters: [],
      responses: [
        { statusCode: 201, description: 'Создано', contentType: 'application/json', schemaId: 'OrderResponse' }
      ],
      security: [{ type: 'jwt', scopes: ['orders.write'], description: 'JWT authentication' }],
      rateLimiting: { enabled: true, limit: 100, period: 'hour', perUser: true },
      dependencies: [],
      generatedEvents: ['order.created'],
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '3',
      method: 'GET',
      path: '/api/v1/products',
      serviceName: 'Product Service',
      summary: 'Get products',
      description: 'Получить список продуктов',
      tags: ['Products'],
      status: 'missing',
      useCaseId: 'UC-07',
      requirementIds: [],
      parameters: [],
      responses: [
        { statusCode: 200, description: 'Успешно', contentType: 'application/json' }
      ],
      security: [{ type: 'none', scopes: [] }],
      dependencies: [],
      generatedEvents: [],
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      id: '4',
      method: 'SUBSCRIBE',
      path: 'order.created',
      serviceName: 'Notification Service',
      summary: 'Order created event',
      description: 'Подписка на событие создания заказа',
      tags: ['Events'],
      status: 'ready',
      useCaseId: 'UC-15',
      requirementIds: [],
      parameters: [],
      responses: [],
      security: [{ type: 'none', scopes: [] }],
      dependencies: [],
      generatedEvents: [],
      createdAt: new Date(),
      updatedAt: new Date()
    }
  ];

  const mockSchemas: DataSchema[] = [
    {
      id: '1',
      name: 'Order',
      type: 'object',
      description: 'Представляет заказ в системе',
      properties: [
        { id: '1', name: 'id', type: 'string', required: true, description: 'UUID заказа', example: 'ord_123' },
        { id: '2', name: 'userId', type: 'string', required: true, description: 'ID пользователя', example: 'usr_456' },
        { id: '3', name: 'status', type: 'string', required: true, description: 'Статус заказа', example: 'processing' },
        { id: '4', name: 'totalAmount', type: 'number', required: true, description: 'Сумма заказа', example: 199.99, validation: { minimum: 0 } },
        { id: '5', name: 'createdAt', type: 'string', required: true, description: 'Дата создания', example: '2024-01-15T10:30:00Z', validation: { format: 'date-time' } }
      ],
      required: ['id', 'userId', 'status', 'totalAmount', 'createdAt'],
      linkedToDbTable: 'orders',
      usedInEndpoints: ['1', '2'],
      createdAt: new Date()
    },
    {
      id: '2',
      name: 'OrderListResponse',
      type: 'object',
      description: 'Ответ со списком заказов',
      properties: [
        { id: '1', name: 'data', type: 'array', required: true, description: 'Массив заказов', reference: 'Order[]' },
        { id: '2', name: 'meta', type: 'object', required: true, description: 'Метаданные пагинации', reference: 'PaginationMeta' }
      ],
      required: ['data', 'meta'],
      usedInEndpoints: ['1'],
      createdAt: new Date()
    },
    {
      id: '3',
      name: 'OrderResponse',
      type: 'object',
      description: 'Ответ с одним заказом',
      properties: [
        { id: '1', name: 'data', type: 'object', required: true, description: 'Данные заказа', reference: 'Order' }
      ],
      required: ['data'],
      usedInEndpoints: ['2'],
      createdAt: new Date()
    }
  ];

  const mockEvents: ApiEvent[] = [
    {
      id: '1',
      name: 'order.created',
      description: 'Генерируется при создании нового заказа',
      sourceService: 'Order Service',
      triggerEndpoint: 'POST /api/v1/orders',
      protocol: 'kafka',
      topic: 'orders',
      payloadSchemaId: 'OrderCreatedEvent',
      consumers: [
        { id: '1', serviceName: 'Notification Service', description: 'Отправка email клиенту', status: 'active', lastProcessed: new Date() },
        { id: '2', serviceName: 'Analytics Service', description: 'Запись в лог аналитики', status: 'active' },
        { id: '3', serviceName: 'Inventory Service', description: 'Обновление остатков', status: 'active' }
      ],
      webhooks: [
        { id: '1', url: 'https://partner.com/webhook', method: 'POST', headers: { 'X-API-Key': '***' }, status: 'active', lastTriggered: new Date(Date.now() - 600000) }
      ],
      retryPolicy: { maxAttempts: 3, backoffType: 'exponential', timeoutSeconds: 30, deadLetterQueue: true },
      createdAt: new Date()
    },
    {
      id: '2',
      name: 'payment.succeeded',
      description: 'Успешный платеж',
      sourceService: 'Payment Service',
      protocol: 'kafka',
      topic: 'payments',
      payloadSchemaId: 'PaymentEvent',
      consumers: [
        { id: '1', serviceName: 'Order Service', description: 'Обновление статуса заказа', status: 'active' }
      ],
      webhooks: [],
      retryPolicy: { maxAttempts: 3, backoffType: 'exponential', timeoutSeconds: 30, deadLetterQueue: true },
      createdAt: new Date()
    },
    {
      id: '3',
      name: 'payment.failed',
      description: 'Неудачный платеж',
      sourceService: 'Payment Service',
      protocol: 'kafka',
      topic: 'payments',
      payloadSchemaId: 'PaymentEvent',
      consumers: [
        { id: '1', serviceName: 'Notification Service', description: 'Уведомление клиента', status: 'active' }
      ],
      webhooks: [],
      retryPolicy: { maxAttempts: 3, backoffType: 'exponential', timeoutSeconds: 30, deadLetterQueue: true },
      createdAt: new Date()
    }
  ];

  const handleCreateEndpoint = () => {
    setSelectedEndpoint(undefined);
    setActiveView('endpoint');
  };

  const handleEditEndpoint = (endpoint: ApiEndpoint) => {
    setSelectedEndpoint(endpoint);
    setActiveView('endpoint');
  };

  const handleSaveEndpoint = async (endpoint: Partial<ApiEndpoint>) => {
    try {
      if (selectedEndpoint) {
        await apiClient.updateEndpoint(parseInt(selectedEndpoint.id), endpoint);
      } else {
        await apiClient.createEndpoint(endpoint);
      }
      await loadData();
      setActiveView('dashboard');
    } catch (error) {
      console.error('Failed to save endpoint:', error);
      alert('Ошибка при сохранении endpoint');
    }
  };

  return (
    <div className="h-screen bg-background">
      <header className="border-b border-border px-6 py-3 flex items-center justify-between">
        <div className="flex items-center gap-4">
          <div className="flex items-center gap-2">
            <Icon name="Code" size={24} className="text-primary" />
            <h1 className="text-xl font-bold">API Design Studio</h1>
          </div>
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <Icon name="Folder" size={16} />
            <span>E-Commerce Platform</span>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <Button
            variant={activeView === 'dashboard' ? 'default' : 'ghost'}
            size="sm"
            onClick={() => setActiveView('dashboard')}
          >
            <Icon name="LayoutDashboard" size={14} className="mr-2" />
            Dashboard
          </Button>
          <Button
            variant={activeView === 'schema' ? 'default' : 'ghost'}
            size="sm"
            onClick={() => setActiveView('schema')}
          >
            <Icon name="Database" size={14} className="mr-2" />
            Схемы
          </Button>
          <Button
            variant={activeView === 'event' ? 'default' : 'ghost'}
            size="sm"
            onClick={() => setActiveView('event')}
          >
            <Icon name="Zap" size={14} className="mr-2" />
            События
          </Button>
          <Button
            variant={activeView === 'docs' ? 'default' : 'ghost'}
            size="sm"
            onClick={() => setActiveView('docs')}
          >
            <Icon name="FileText" size={14} className="mr-2" />
            Документация
          </Button>
          <Button
            variant={activeView === 'code' ? 'default' : 'ghost'}
            size="sm"
            onClick={() => setActiveView('code')}
          >
            <Icon name="Terminal" size={14} className="mr-2" />
            Генерация кода
          </Button>
        </div>
      </header>

      <main className="h-[calc(100vh-60px)]">
        {loading ? (
          <div className="h-full flex items-center justify-center">
            <div className="text-center">
              <Icon name="Loader2" size={48} className="animate-spin mx-auto mb-4 text-primary" />
              <p className="text-muted-foreground">Загрузка API Design Studio...</p>
            </div>
          </div>
        ) : activeView === 'dashboard' ? (
          <ApiDashboard
            services={services.length > 0 ? services : mockServices}
            endpoints={endpoints.length > 0 ? endpoints : mockEndpoints}
            onCreateEndpoint={handleCreateEndpoint}
            onEditEndpoint={handleEditEndpoint}
            onSyncWithUseCases={() => console.log('Sync with use cases')}
            onAutoGenerate={() => console.log('Auto generate')}
          />
        ) : null}

        {!loading && activeView === 'dashboard' && (
          <></>
        )}

        {activeView === 'endpoint' && (
          <EndpointEditor
            endpoint={selectedEndpoint}
            onSave={handleSaveEndpoint}
            onClose={() => setActiveView('dashboard')}
          />
        )}

        {activeView === 'schema' && (
          <SchemaDesigner
            schemas={mockSchemas}
            onCreateSchema={() => console.log('Create schema')}
            onEditSchema={(schema) => console.log('Edit schema:', schema)}
            onClose={() => setActiveView('dashboard')}
          />
        )}

        {activeView === 'event' && (
          <EventDesigner
            events={mockEvents}
            onCreateEvent={() => console.log('Create event')}
            onClose={() => setActiveView('dashboard')}
          />
        )}

        {activeView === 'docs' && (
          <DocumentationGenerator onClose={() => setActiveView('dashboard')} />
        )}

        {activeView === 'code' && (
          <CodeGenerator onClose={() => setActiveView('dashboard')} />
        )}
      </main>
    </div>
  );
}